"""add activity comment notification models

Revision ID: 93b7caf9cb2c
Revises: 3f1a9c2b7d40
Create Date: 2026-07-27 12:56:53.385364
"""
from alembic import op
import sqlalchemy as sa


revision = '93b7caf9cb2c'
down_revision = '3f1a9c2b7d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('workspace_activities',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_activities_user_id'), 'workspace_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_activities_workspace_id'), 'workspace_activities', ['workspace_id'], unique=False)
    op.create_table('page_comments',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_comments_page_id'), 'page_comments', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_comments_user_id'), 'page_comments', ['user_id'], unique=False)
    op.create_table('page_presences',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_presences_page_id'), 'page_presences', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_presences_user_id'), 'page_presences', ['user_id'], unique=False)
    op.create_index(op.f('ix_page_presences_workspace_id'), 'page_presences', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_presences_workspace_id'), table_name='page_presences')
    op.drop_index(op.f('ix_page_presences_user_id'), table_name='page_presences')
    op.drop_index(op.f('ix_page_presences_page_id'), table_name='page_presences')
    op.drop_table('page_presences')
    op.drop_index(op.f('ix_page_comments_user_id'), table_name='page_comments')
    op.drop_index(op.f('ix_page_comments_page_id'), table_name='page_comments')
    op.drop_table('page_comments')
    op.drop_index(op.f('ix_workspace_activities_workspace_id'), table_name='workspace_activities')
    op.drop_index(op.f('ix_workspace_activities_user_id'), table_name='workspace_activities')
    op.drop_table('workspace_activities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
